name: "Tests"

on:
  push:
    branches: [ master, develop ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ develop ]
  schedule:
    - cron: '55 22 15 * *'

jobs:
  pytest:
    name: pytest
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [3.6, 3.7, 3.8, 3.9]
        django: [1.11, 2.0, 2.1, 2.2, 3.0, 3.1, 3.2]
        database: [postgres, sqlite]
        exclude:
          - python: 3.8
            django: 1.11
          - python: 3.8
            django: 2.0
          - python: 3.8
            django: 2.1
          - python: 3.9
            django: 1.11
          - python: 3.9
            django: 2.0
          - python: 3.9
            django: 2.1

    services:
      # as far as I can see, no way to make this conditional on the matrix database
      postgres:
        image: postgres:9.6
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: dirtyfields_test
        ports:
          - 5432:5432

    env:
      TEST_DATABASE: ${{ matrix.database }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - name: Install test requirements
        run: |
          python -m pip install --upgrade pip wheel
          pip install django~=${{ matrix.django }}.0 -r tests-requirements.txt .
          python --version
          pip freeze -l

      - name: Run unit tests
        run: python -m pytest
