name: "Tests"

on:
  push:
    branches: [ master, develop ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ develop ]
  schedule:
    - cron: '55 22 15 * *'

jobs:
  pytest:
    name: pytest
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ['3.6', '3.7', '3.8', '3.9']
        django: ['1.11', '2.0', '2.1', '2.2', '3.0', '3.1', '3.2']
        database: ['postgres', 'sqlite']
        exclude:
          - python: '3.8'
            django: '1.11'
          - python: '3.8'
            django: '2.0'
          - python: '3.8'
            django: '2.1'
          - python: '3.9'
            django: '1.11'
          - python: '3.9'
            django: '2.0'
          - python: '3.9'
            django: '2.1'

    services:
      # as far as I can see, no way to make this conditional on the matrix database
      postgres:
        image: postgres:9.6
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: dirtyfields_test
        ports:
          - 5432:5432

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - name: Install test requirements
        run: |
          python -m pip install --upgrade pip wheel
          pip install django~=${{ matrix.django }}.0 coverage[toml] coveralls -r tests-requirements.txt .
          python --version
          pip list

      - name: Run unit tests
        run: coverage run -m pytest -v
        env:
          TEST_DATABASE: ${{ matrix.database }}

      - name: Report coverage to console
        run: coverage report

      - name: Report coverage to coveralls.io
        run: coveralls --service=github
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COVERALLS_FLAG_NAME: python-${{ matrix.python }}-django-${{ matrix.django }}-${{ matrix.database }}
          COVERALLS_PARALLEL: true

  coveralls-finished:
    name: Tell coveralls.io test matrix is finished
    needs: pytest
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install requirements
        run: pip install --upgrade coveralls

      - name: Tell coveralls.io test matrix is finished
        run: coveralls --service=github --finish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
